# Generated by Django 3.0.2 on 2020-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('chat', '0003_auto_20200122_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='_chat_messages_+', to='message.Message'),
        ),
    ]
