# Generated by Django 3.0.2 on 2020-03-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
